### ISSUE TITLE
Setting the environment variables

### ISSUE THREAD

**Issue by brunopulis** [benbarber/jekyll-instagram#4]
Good afternoon @benbarber , I'm trying to use the plugin, however, I don't know where I set the environment variables, can you help me? 

I did a Google search, but I didn't find any good references.

**Comment by zachwright** [comment]
Hey @brunopulis, I can try to help you, too. 

If you just want to see it working locally, you'll want to add the key as an environment variable on your local machine.

https://medium.com/@himanshuagarwal1395/setting-up-environment-variables-in-macos-sierra-f5978369b255 This article illustrates how to do so, but in short, you'll want to open up your `.bash_profile` (if you are using bash) or your `.zshrc` (if you are using zsh) in nano, vim, or vscode, and add `export JEKYLLGRAM_TOKEN=""`(where your token from Instagram goes in the double quotes `""`).

```bash
vim ~/.bash_profile
```

Add this line to the file
```bash
export JEKYLLGRAM_TOKEN="some-token-string-here"
```

**Comment by brunopulis** [comment]
> Hey @brunopulis, I can try to help you, too.
> 
> If you just want to see it working locally, you'll want to add the key as an environment variable on your local machine.
> 
> https://medium.com/@himanshuagarwal1395/setting-up-environment-variables-in-macos-sierra-f5978369b255 This article illustrates how to do so, but in short, you'll want to open up your `.bash_profile` (if you are using bash) or your `.zshrc` (if you are using zsh) in nano, vim, or vscode, and add `export JEKYLLGRAM_TOKEN=""`(where your token from Instagram goes in the double quotes `""`).
> 
> ```shell
> vim ~/.bash_profile
> ```
> 
> Add this line to the file
> 
> ```shell
> export JEKYLLGRAM_TOKEN="some-token-string-here"
> ```

Hey @zachwright thank you so much I'll try :)

**Comment by beebul** [comment]
But how do you get this working on a production version running on GitHub pages?

**Comment by benbarber** [comment]
@beebul you would run the build locally and then push the statically generated site to a `gh-pages` branch in your GitHub repo.

**Comment by benbarber** [comment]
Closing this as @brunopulis original issue is resolved.
